shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
]

shop/myshop/urls.py
from django.urls import path
from . import views

app_name = 'myshop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('delivery/', views.delivery_view, name='delivery'),
    path('about_pay/', views.about_pay_view, name='about_pay'),
    path('contact/', views.contact_view, name='contact'),
    path('reviews/', views.reviews_view, name='reviews'),
    path('network/', views.network_view, name='network'),

    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from myshop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('myshop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/myshop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='media/photos_categories/', blank=True, verbose_name='Фото категории')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='category',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True, verbose_name='Названия')
    slug = models.CharField(max_length=150, db_index=True, unique=True, verbose_name='Ссылка')
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    price = models.IntegerField(verbose_name='Цена')
    image = models.ImageField(upload_to='media/photos_product/', blank=True, verbose_name='Фото')
    discount = models.IntegerField(verbose_name='Скидка(Сумма)', blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])

    def get_discounted_price(self):
        return self.price - self.discount

class PhotoSlider(models.Model):
    image = models.ImageField(upload_to='media/photos_slider/', verbose_name='Фото')

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name_plural = 'Фото для слайда'
        verbose_name = 'Фото для слайда'

shop/myshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, PhotoSlider
from cart.forms import CartAddProductForm


def delivery_view(request):
    return render(request, 'myshop/product/delivery.html')


def about_pay_view(request):
    return render(request, 'myshop/product/about_pay.html')


def contact_view(request):
    return render(request, 'myshop/product/contact.html')


def reviews_view(request):
    return render(request, 'myshop/product/reviews.html')


def network_view(request):
    return render(request, 'myshop/product/network.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    photo_slider = PhotoSlider.objects.all()
    cart_product_form = CartAddProductForm()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'myshop/product/product_list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products,
                      'photo_slider': photo_slider,
                      'cart_product_form': cart_product_form,
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'myshop/product/product_detail.html', {'product': product,
                                                                  'cart_product_form': cart_product_form,
                                                                  })

shop/myshop/templates/myshop/product/about_pay.html
{% extends "myshop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div class="block_pay">
    <h2>Информация об оплате</h2>
    <p>
        Мы принимаем наличные средства, банковские карты (VISA, MasterCard и МИР),
        электронные деньги, безналичные расчеты от физических и юридических лиц.
        У нас нету минимальной суммы заказа, Вы можете заказывать продукцию
        от любого количества и суммы.
        А также можете оплатить напрямую нашему менеджеру: @Команда Войковская
    </p>
</div>


<div class="cart_link">
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
        <button>
            <a href="{% url 'cart:cart_detail' %}">
                Корзина ({{ total_items }})
            </a>
        </button>

    {% else %}

    {% endif %}
    {% endwith %}
</div>    
<p class="text-right">
    <button>
        <a href="{% url 'myshop:product_list' %}">Вернуться к продуктам</a>
    </button>
</p>
    
{% endblock %}

shop/myshop/templates/myshop/product/contact.html
{% extends "myshop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div class="block_con">
    <h2>Контактная информация</h2>
    <p>
        Наши менеджеры всегда на связи 24/7,
        по каким либо вопросам, пишите в службу поддержки
    </p>
    <div class="address_about">
        Наш адрес: Озёрная ул., 44
    </div>
    <div>
        Номер телефона: +7 (969) 238-48-88
    </div>
</div>

<div class="tg_button">
    <p class="text-right">
        <button>
            <a href="https://t.me/LouisBurger44">Наш телеграм канал</a>
        </button>
    </p>
</div>



<div class="cart_link">
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
        <button>
            <a href="{% url 'cart:cart_detail' %}">
                Корзина ({{ total_items }})
            </a>
        </button>

    {% else %}

    {% endif %}
    {% endwith %}
</div>   

<div class="div_but_product">
    <p class="text-right">
        <button>
            <a href="{% url 'myshop:product_list' %}">Вернуться к продуктам</a>
        </button>
    </p>
</div>

    
{% endblock %}

shop/myshop/templates/myshop/product/delivery.html
{% extends "myshop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div class="block_delivery">
    <h2>Информация о доставке</h2>
    <p>
        После того, как Вы сделали заказ, наши менеджеры связываются с Вами для подтверждения заказа
    </p>

    <h2>
        Доставка курьером по г. Москва
    </h2>

    <p>
        Стоимость доставки по г. Москва в пределах - 500 руб.
        При заказе на сумму от 10000 руб. - доставка осуществляется бесплатно в пределах города.
    </p>
</div>


<div class="cart_link">
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
        <button>
            <a href="{% url 'cart:cart_detail' %}">
                Корзина ({{ total_items }})
            </a>
        </button>

    {% else %}

    {% endif %}
    {% endwith %}
</div>    
<p class="text-right">
    <button>
        <a href="{% url 'myshop:product_list' %}">Вернуться к продуктам</a>
    </button>
</p>
    
{% endblock %}

shop/myshop/templates/myshop/product/product_detail.html
{% extends "myshop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<header>
    <button class="detail-krest">
        <a href="{% url 'shop:product_list' %}">В МАГАЗИН
        </a> 
    </button>
</header>

<div class="product-detail">
    <img class="photo_product_detail" src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static 'img/no_image.png' %}{% endif %}">
    <div class="text_detail">
        <h5>
            {{ product.category }}
        </h5>
    
        <h1 class="price">
            {{ product.price }} ₽
        </h1>
    
        <h2 class="name_product">
            {{ product.name }}
        </h2>
    
        <h6 class="discription_product">
            {{ product.description|linebreaks }}<br>
        </h6>
    </div>
    <form class="count" action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input class="button-container" type="submit" value="В корзину">
    </form>
</div>
{% endblock %}

shop/myshop/templates/myshop/product/product_list.html
{% extends "myshop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}


<div class="slider">
    {% for photo in photo_slider %}
    <img src="{{ photo.image.url }}" class="slide">
    {% endfor %}
</div>


<div class="blocks">
    <div class="menu">
        <ul>
            <li>
                <button>
                    <a href="{% url 'myshop:delivery' %}">Доставка</a>
                </button>
            </li>
            <li>
                <button>
                    <a href="{% url 'myshop:about_pay' %}">Оплата</a>
                </button>
    
            </li>
            <li>
                <button>
                    <a href="{% url 'myshop:contact' %}">Контакты</a>
                </button>
            </li>
            <li>
                <button>
                    <a href="{% url 'myshop:reviews' %}">Отзывы</a>
                </button>
            </li>
        </ul>
    </div>
    
    
    <div class="cat_prod">
        <div id="category" class="product-categories">
            <div>
                {% for c in categories %}
                <div class="category">
                    <a href="{{ c.get_absolute_url }}">
                    <img class="photo_category"
                    src="{% if c.image %}{{ c.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                    </a>
                    <div>
    
                    </div>
                    <a class="text_categories" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </div>
                {% endfor %}
            </div>
        </div>
    
        <div id="main" class="product-list">
            {% for product in products %}
            <div class="item">
                <a class="item_product" href="{{ product.get_absolute_url }}">
    
                    <img class="photo_product"
                         src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                    <div class="text_product">
                        <h6>{{ product.category }}</h6>
                        <h5>{{ product.name }}</h5>
                        {% if product.discount == 0 %}
                            <h3>{{ product.price }} ₽</h3>
                        {% else %}
                        <div class="price_dis">
                            <h3>{{ product.get_discounted_price }} ₽</h3>
                            <div class="old_price">{{ product.price }} ₽</div>
    
                        </div>
    
                        {% endif %}
                    </div>
    
                </a>
    
                <form class="button_add" action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="В корзину">
                </form>
    
            </div>
        
    
            {% endfor %}
        </div>
    </div>
</div>


<div class="cart_link">
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
        <button>
            <a href="{% url 'cart:cart_detail' %}">
                Корзина ({{ total_items }})
            </a>
        </button>

    {% else %}

    {% endif %}
    {% endwith %}
</div>
{% endblock %}
<script src="{% static 'js/script.js' %}"></script>

shop/myshop/templates/myshop/product/reviews.html
{% extends "myshop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div class="block_con">
    <h2>Отзывы клиентов</h2>
    <p>
        Вам у нас понравилось? Оставьте отзыв по ссылке ниже
    </p>
</div>

<div class="tg_button">
    <p class="text-right">
        <button>
            <a href="https://yandex.ru/maps/org/louis_burger/17387177709/reviews/?ll=37.440245%2C55.667666&z=17">
                Оставить отзыв
            </a>
        </button>
    </p>
</div>



<div class="cart_link">
    {% with total_items=cart|length %}
    {% if cart|length > 0 %}
        <button>
            <a href="{% url 'cart:cart_detail' %}">
                Корзина ({{ total_items }})
            </a>
        </button>

    {% else %}

    {% endif %}
    {% endwith %}
</div>   

<div class="div_but_product">
    <p class="text-right">
        <button>
            <a href="{% url 'myshop:product_list' %}">Вернуться к продуктам</a>
        </button>
    </p>
</div>

    
{% endblock %}